create table questions
(
    id                             bigserial primary key,
    author_id                      bigint,
    author_role                    bigint,
    status                         bigint,
    question_type                  bigint,
    data_type                      bigint,
    question_value                 text,
    question_label                 text,
    prompt_text                    text,
    required_answer                boolean,
    allow_multiple_answer          boolean,
    historically_tracked_parameter boolean,
    parent_question_id             bigint,
    answer_values                  jsonb,
    multiple_selection             boolean,
    min_additions                  double precision,
    max_additions                  double precision,
    min_symbols                    bigint,
    max_symbols                    bigint,
    rows_number                    bigint,
    keywords_recognize             boolean,
    date_type                      bigint,
    allow_current_and_future_date  boolean,
    allow_approximate_date         boolean,
    measurement_units              jsonb,
    default_measurement_unit       bigint,
    max_value                      double precision,
    min_value                      double precision,
    attachment_formats             jsonb,
    created_table                  jsonb,
    ref_book                       jsonb,
    allow_other                    boolean,
    med_data_type                  bigint,
    biomarker                      bigint,
    additional_question_influence  boolean,
    default_chapter                bigint,
    default_block                  bigint,
    destination_chapters           jsonb,
    destination_blocks             jsonb,
    age_groups                     bigint,
    genders                        jsonb,
    comment                        text,
    notification                   text,
    divider                        boolean
);